### ISSUE TITLE
Heorku Deployment

### ISSUE THREAD

**Issue by zack-w** [opoll/openpoll-schemas#12]
- [x] setup dns entry for schemas.openpoll.io
- [x] create heroku instance for schemas hosting
- [x] deploy & test schemas.openpoll.io
- [x] setup automated schemas heroku deployments

**Comment by zack-w** [comment]
done

**Comment by Cyberuben** [comment]
Could you force the connection to use HTTPS instead? It also needs an update of @openpoll/schemas, so could you bump that version by running `npm install @openpoll/schemas@1.0.13` (I think this is the latest), then push it again?
